spring:
  application:
    name: rpamis-architecture-build
  datasource:
    url: jdbc:mysql://localhost:3306/db?characterEncoding=utf-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8180
  servlet:
    context-path: /rpamis-architecture-build

cache:
  enums:
    packages:
      - com.rpamis.common.dto.enums
      - com.rpamis.architecture.consts
    enabled: true