# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Strong CI with multiply java versions
on: [ push, pull_request, workflow_dispatch ]
jobs:
  # job 1: Test based on java 8 Do not checkstyle.
  build:
    name: "build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17, 21 ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v3
      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      # step 3
      - name: "Print maven version"
        run: ./mvnw -version
      # step 4.1
      - name: "Test, Check style, Check PMD, Check license with Maven and Java8"
        if: matrix.java == '8'
        run: |
          ./mvnw -T 4C clean test \
                 -Dcheckstyle.skip=false -Dpmd.skip=false -Dlicense.skip=false -DredisCaseEnabled=true \
                 -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
      # step 4.2
      - name: "Test with Maven and Java${{ matrix.java }}"
        if: matrix.java != '8'
        run: |
          ./mvnw -T 4C clean test \
                 -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
      # step 5
#      - name: "Codecov"
#        if: matrix.java == '8'
#        uses: codecov/codecov-action@v4.0.1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          version: v0.6.0
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
